name: Cypress develop
on:
  pull_request:
    branches: develop

jobs:
  cypress_tests_dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout frontend repository
      uses: actions/checkout@v2

    - name: Checkout backend repository
      uses: actions/checkout@v2
      with:
        repository: echo-webkom/echo-web-backend
        path: backend
        ref: develop

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build frontend with cache
      run: |
        docker build \
          --cache-from "$USERNAME/$IMAGE_NAME:$TAG" \
          -t "$USERNAME/$IMAGE_NAME:$TAG" \
          -t "$USERNAME/$IMAGE_NAME:$COMMIT_SHA" \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          .
        docker push "$USERNAME/$IMAGE_NAME" --all-tags
      env:
        DOCKER_BUILDKIT: 1
        USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        IMAGE_NAME: echo-web-frontend
        TAG: latest-dev
        COMMIT_SHA: ${{ github.sha }}

    - name: Build backend with cache
      run: |
        docker build \
          --cache-from "$USERNAME/$IMAGE_NAME:$TAG" \
          -t "$USERNAME/$IMAGE_NAME:$TAG" \
          -t "$USERNAME/$IMAGE_NAME:$COMMIT_SHA" \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          backend
        docker push "$USERNAME/$IMAGE_NAME" --all-tags
      env:
        DOCKER_BUILDKIT: 1
        USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        IMAGE_NAME: echo-web-backend
        TAG: latest-dev
        COMMIT_SHA: ${{ github.sha }}

    - name: Run Cypress end-to-end tests against develop backend
      run: docker-compose -f $COMPOSE_FILE up --exit-code-from=frontend
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        TAG: ${{ github.sha }}
        CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID_TESTING }}
        CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN_TESTING }}
        CONTENTFUL_ENVIRONMENT_ID: testing
        ADMIN_KEY: admin-passord
        COMPOSE_FILE: docker-compose.ci.yaml
